name: Daily ETL

on:
  schedule:
    - cron: "0 17 * * *"  # 1 AM MYT
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Use the same interpreter as setup-python
      - name: Install dependencies
        run: |
          $PY = "${{ steps.setup.outputs.python-path }}"
          & $PY -m pip install --upgrade pip
          & $PY -m pip install --force-reinstall pandas numpy yfinance psycopg2-binary sqlalchemy python-dotenv matplotlib scikit-learn
          & $PY - << 'PYEND'
          import sys
          print("Using Python:", sys.executable)
          import pandas, numpy, yfinance, sqlalchemy, dotenv
          print("All imports OK")
          PYEND
        shell: pwsh

      - name: Run ETL
        run: |
          $PY = "${{ steps.setup.outputs.python-path }}"
          & $PY run_etl.py
        shell: pwsh
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
