name: Daily ETL

on:
  schedule:
    - cron: "0 17 * * *"   # 1:00 AM MYT daily
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Capture python path
        shell: powershell
        run: |
          echo "PY=${{ steps.setup.outputs.python-path }}" >> $env:GITHUB_ENV

      - name: Debug python being used
        shell: powershell
        run: |
          Write-Host "python path (env): $env:PY"
          & $env:PY --version
          & $env:PY -c "import sys; print('sys.executable =', sys.executable)"

      - name: Install dependencies
        shell: powershell
        run: |
          & $env:PY -m pip install --upgrade pip
          & $env:PY -m pip install pandas numpy yfinance psycopg2-binary sqlalchemy python-dotenv matplotlib scikit-learn

      - name: Run ETL Script
        shell: powershell
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        run: |
          & $env:PY "run_etl.py"

