name: Daily ETL

on:
  schedule:
    - cron: "0 17 * * *"  # 1 AM MYT daily
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Grab the absolute path to the interpreter that setup-python installed
      - name: Capture python path
        shell: pwsh
        run: echo "PY=$env:pythonLocation\python.exe" >> $env:GITHUB_ENV

      - name: Install dependencies (force, same interpreter)
        shell: pwsh
        run: |
          & $env:PY -m pip install --upgrade pip
          & $env:PY -m pip install pandas numpy yfinance psycopg2-binary sqlalchemy python-dotenv matplotlib scikit-learn
          & $env:PY - << 'PYEND'
          import sys
          print("Using:", sys.executable)
          import pandas, numpy, yfinance, dotenv, sqlalchemy
          print("All imports OK")
          PYEND

      - name: Run ETL Script (same interpreter)
        shell: pwsh
        run: |
          & $env:PY run_etl.py
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets_POSTGRES_PORT }}
