name: Daily ETL

on:
  schedule:
    - cron: "0 17 * * *"  # Runs daily at 1 AM MYT (17:00 UTC)
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-etl:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-dotenv
          pip install -r requirements.txt

      - name: Check dotenv installed
        run: python -c "import dotenv; print('dotenv installed OK')"

      - name: Run ETL Script
        run: python run_etl.py
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
